image: ubuntu:latest

stages:
  - before_script
  - build
  - test


before_script:
  - apt-get update -y
  - apt-get install -y build-essential
  - apt-get install qtbase6-dev qt6-qmake qtbase6-dev-tools


build:
  stage: build
  script:
    - qmake ./HTML_editor.pro
    - make -j$(nproc)

test:
  stage: test
  script:
    - cd test
    - for dir in */; do
        if [[ $dir == *Test/ ]]; then
          cd $dir;
          qmake;
          make;
          ./$(basename $dir)Test;
          cd ..;
        fi
      done
